name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: ai-review.mjs
      id: ai-review-mjs
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: ai-review.mjs
        setup-command: npm install
        command: npm test
        timeout: 10
        max-score: 100
    - name: ai-review.yml
      id: ai-review-yml
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: ai-review.yml
        setup-command: npm install
        command: npm test
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        AI-REVIEW-MJS_RESULTS: "${{steps.ai-review-mjs.outputs.result}}"
        AI-REVIEW-YML_RESULTS: "${{steps.ai-review-yml.outputs.result}}"
      with:
        runners: ai-review-mjs,ai-review-yml
